import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Providers from "./providers";
import "./globals.css";

const inter = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body
				suppressHydrationWarning={true}
				className={inter.className + "h-full font-sans antialiased text-white"}
			>
				<Providers>
					<main className="flex flex-col min-h-screen">{children}</main>
				</Providers>
			</body>
		</html>
	);
}
